#!/usr/bin/env python3
"""
Linter de dette IA : scanne le code d'un repo (ou d'un dossier de repos) et
compte les anti-patterns de dette technique generee par IA, selon un
sous-ensemble lintable des 15 commandements d'Alexandre Picard (formation IIM).

Outil 100% DETERMINISTE : aucun appel LLM, que du regex et du parsing de
fichiers. Meme repo en entree => meme rapport en sortie. C'est le coeur du
message pedagogique (commandement #6 : script deterministe > LLM).

Usage:
    python lint_dette_ia.py <chemin_repo>           # scan d'un seul repo -> JSON
    python lint_dette_ia.py --all <dossier_repos>   # scan de N repos -> JSON agrege
    python lint_dette_ia.py <chemin_repo> --pretty  # JSON indente
    python lint_dette_ia.py --all ./repos > rapport.json

Sortie (un repo) :
    {"repo": "...", "etudiant": "...", "total": 23, "parRegle": {...},
     "exemples": [{"regle": "...", "fichier": "...", "ligne": 1, "detail": "..."}]}

Le mode --all sort un tableau de ces objets.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime
from pathlib import Path

# --------------------------------------------------------------------------
# Configuration du scan
# --------------------------------------------------------------------------

# Dossiers ignores (bruit, dependances, artefacts de build, code genere)
IGNORE_DIRS = {
    'node_modules', '.git', 'dist', 'build', '.next', 'out', 'coverage',
    '.cache', '.turbo', '.vercel', 'vendor', '.venv', 'venv', '__pycache__',
    '.idea', '.vscode', '.svelte-kit', 'generated', '__generated__', '.prisma',
    'migrations',
}

# Marqueur de fichier genere (place en tete par les generateurs : Prisma, GraphQL
# codegen, protobuf, etc.). Le code genere n'est PAS la dette de l'etudiant : on
# le saute entierement. Detection deterministe sur les 15 premieres lignes.
GENERATED_MARKERS = re.compile(
    r'(generated by|do not edit|@generated|auto[- ]?generated'
    r'|automatically generated|code generated)',
    re.IGNORECASE,
)

# Fichiers ignores en entier (lockfiles, manifestes volumineux non pertinents)
IGNORE_FILES = {
    'package-lock.json', 'yarn.lock', 'pnpm-lock.yaml', 'bun.lockb',
    'composer.lock', 'poetry.lock',
}

# Extensions scannees ligne a ligne (les etudiants codent en JS/TS)
SCAN_EXTENSIONS = {
    '.js', '.jsx', '.ts', '.tsx', '.mjs', '.cjs',
    '.vue', '.svelte', '.astro', '.py',
}

# Au-dela : on considere une ligne comme minifiee et on saute le fichier
MAX_LINE_LENGTH_BEFORE_MINIFIED = 1000

# Seuils god-file (nombre de lignes)
GOD_FILE_WARNING = 300
GOD_FILE_GRAVE = 500

# Noms de fichiers fourre-tout (stem exact, sans extension)
LAZY_FILE_STEMS = {
    'utils', 'util', 'helpers', 'helper', 'misc', 'data', 'temp', 'tmp',
    'stuff', 'config', 'common', 'things',
}
# Fichiers de test/seed/mock/fixture : un mot de passe ou un console.log y est
# attendu (fixture, assertion) -> pas un vrai secret ni de la dette shippable.
# On y desactive les regles bruyantes (secret-en-clair, logs-oublies).
SKIP_LOGS_FILE_HINT = re.compile(
    r'(seed|fixture|mock|__mocks__|\.(test|spec)\.|/tests?/|__tests__)',
    re.IGNORECASE,
)

# Fichiers de cadrage acceptes a la racine (commandement #1/#5)
FRAMING_FILES = {'claude.md', 'project_rules.md', 'agents.md', 'cursor.md'}

# Nombre max d'exemples conserves par regle dans le rapport
MAX_EXAMPLES_PER_RULE = 8
# Nombre de lignes de contexte affichees avant/apres la ligne fautive (vue GitHub)
CONTEXT_RADIUS = 2
# Longueur max d'une ligne de code affichee (au-dela : tronquee)
MAX_CODE_LINE_LENGTH = 200

# --------------------------------------------------------------------------
# Definition des regles (libelles francais + regex deterministes)
# --------------------------------------------------------------------------
# Chaque regle "line" porte une liste de patterns ; un match = un souci.
# On dedupe par (fichier, ligne) a l'interieur d'une meme regle.

RULES_LABELS = {
    'erreur-masquee': 'Erreur masquee (catch vide)',
    'settimeout-magique': 'setTimeout magique (delai arbitraire)',
    'todo-orphelin': 'TODO orphelin',
    'cacher-la-dette': 'Suppression de check (eslint-disable, ts-ignore)',
    'god-file': 'God file (fichier trop long)',
    'logs-oublies': 'Logs / debug oublies',
    'backward-compat': 'Backward compat / code legacy',
    'nommage-paresseux': 'Nommage paresseux (fichier fourre-tout)',
    'pas-de-cadre': 'Pas de cadre (aucun CLAUDE.md)',
    'secret-en-clair': 'Secret en clair',
    'boilerplate-non-modifie': 'Boilerplate non modifie (scaffold brut)',
    'donnees-mockees': 'Donnees mockees (faux backend)',
    'aucun-test': 'Aucun test',
    # --- Securite (inspire des checks entropy TPB) ---
    'xss-innerhtml': 'XSS (dangerouslySetInnerHTML / innerHTML)',
    'eval-dangereux': 'eval / new Function (injection de code)',
    'injection-sql': 'Injection SQL (requete interpolee)',
    'crypto-faible': 'Crypto faible (md5 / sha1)',
    'random-non-securise': 'Math.random pour un secret / id',
    'url-http-non-securisee': 'URL http:// en clair',
    # --- React anti-patterns ---
    'react-hook-sans-deps': 'Hook React sans tableau de dependances',
    'react-key-index': 'key={index} sur une liste',
    # --- Erreurs silencieuses (commandement #9) ---
    'catch-log-seulement': 'Catch qui ne fait que logger',
    'catch-retour-silencieux': 'Catch qui retourne une valeur par defaut',
    # --- Dette / qualite ---
    'type-any': 'Type any (echappatoire TypeScript)',
    'code-commente': 'Code commente (mort)',
    'var-legacy': 'var au lieu de let / const',
    'egalite-non-stricte': 'Egalite non stricte (== / !=)',
    # --- Mode deep : outils externes / AST (option --deep) ---
    'secrets-gitleaks': 'Secret detecte (gitleaks / trivy)',
    'type-errors': 'Erreur de typage (tsc)',
    'duplication': 'Code duplique (jscpd)',
    'fonction-trop-longue': 'Fonction trop longue (AST)',
    'imbrication-profonde': 'Imbrication trop profonde (AST)',
    'import-inutilise': 'Import inutilise (AST)',
}

# Regles du mode deep : seulement remplies quand --deep est utilise (outils ext.)
DEEP_RULES = {
    'secrets-gitleaks', 'type-errors', 'duplication',
    'fonction-trop-longue', 'imbrication-profonde', 'import-inutilise',
}

# Hierarchie de gravite : toutes les regles n'ont pas le meme poids.
# Source de verite du bareme (le dashboard reflete les memes 3 niveaux).
#   critique : faille de securite ou bug silencieux + absence de cadre (Pilier I)
#   majeur   : dette structurelle franche (code mort, non-determinisme, triche)
#   mineur   : bruit / negligence (a nettoyer, mais peu dangereux a l'unite)
SEVERITY_WEIGHT = {'critique': 5, 'majeur': 3, 'mineur': 1}
RULE_SEVERITY = {
    'secret-en-clair': 'critique',
    'erreur-masquee': 'critique',
    'pas-de-cadre': 'critique',
    'boilerplate-non-modifie': 'critique',
    'cacher-la-dette': 'majeur',
    'settimeout-magique': 'majeur',
    'god-file': 'majeur',
    'backward-compat': 'majeur',
    'donnees-mockees': 'majeur',
    'aucun-test': 'majeur',
    'xss-innerhtml': 'critique',
    'eval-dangereux': 'critique',
    'injection-sql': 'critique',
    'crypto-faible': 'majeur',
    'random-non-securise': 'majeur',
    'react-hook-sans-deps': 'majeur',
    'react-key-index': 'majeur',
    'catch-log-seulement': 'majeur',
    'catch-retour-silencieux': 'majeur',
    'type-any': 'majeur',
    'url-http-non-securisee': 'mineur',
    'code-commente': 'mineur',
    'var-legacy': 'mineur',
    'egalite-non-stricte': 'mineur',
    'nommage-paresseux': 'mineur',
    'todo-orphelin': 'mineur',
    'logs-oublies': 'mineur',
    'secrets-gitleaks': 'critique',
    'type-errors': 'majeur',
    'duplication': 'majeur',
    'fonction-trop-longue': 'majeur',
    'imbrication-profonde': 'mineur',
    'import-inutilise': 'mineur',
}

# Patterns regex par regle (rules "ligne", scannees sur le contenu complet).
LINE_RULES: dict[str, list[re.Pattern]] = {
    'erreur-masquee': [
        re.compile(r'catch\s*\([^)]*\)\s*\{\s*\}', re.DOTALL),
        re.compile(r'catch\s*\{\s*\}', re.DOTALL),
        re.compile(r'\.catch\(\s*\(\s*\)\s*=>\s*\{\s*\}\s*\)'),
        re.compile(r'except[^\n:]*:\s*\n\s*pass\b'),
        re.compile(r'except[^\n:]*:\s*pass\b'),
    ],
    'settimeout-magique': [
        re.compile(r'setTimeout\(\s*[^,]+,\s*\d+\s*\)'),
        re.compile(r'setTimeout\(\s*resolve\s*,\s*\d+'),
        re.compile(r'\bsleep\(\s*\d+'),
    ],
    'todo-orphelin': [
        re.compile(r'//\s*(TODO|FIXME|HACK|XXX)\b', re.IGNORECASE),
        re.compile(r'/\*\s*(TODO|FIXME|HACK|XXX)\b', re.IGNORECASE),
        re.compile(r'#\s*(TODO|FIXME|HACK|XXX)\b'),
    ],
    'cacher-la-dette': [
        re.compile(r'eslint-disable'),
        re.compile(r'@ts-ignore'),
        re.compile(r'@ts-nocheck'),
        re.compile(r'@ts-expect-error'),
        re.compile(r'prettier-ignore'),
    ],
    'backward-compat': [
        re.compile(r'\b\w*[lL]egacy\w*\b'),
        re.compile(r'\bdeprecated\b', re.IGNORECASE),
        re.compile(r'\b\w+_old\b'),
        re.compile(r'\b\w+_v[12]\b'),
        re.compile(r'backwardCompat'),
    ],
    'secret-en-clair': [
        re.compile(r'sk-ant-[A-Za-z0-9_-]{8,}'),
        re.compile(r'\bsk-[A-Za-z0-9]{16,}'),
        re.compile(r"""api[_-]?key\s*[:=]\s*['"][^'"\s]+['"]""", re.IGNORECASE),
        re.compile(r"""password\s*[:=]\s*['"][^'"\s]+['"]""", re.IGNORECASE),
    ],
    # --- Securite ---
    'xss-innerhtml': [
        re.compile(r'dangerouslySetInnerHTML'),
        re.compile(r'\.innerHTML\s*='),
        re.compile(r'\.outerHTML\s*='),
        re.compile(r'document\.write\('),
    ],
    'eval-dangereux': [
        re.compile(r'\beval\s*\('),
        re.compile(r'new\s+Function\s*\('),
    ],
    'injection-sql': [
        re.compile(r'`[^`]*\b(SELECT|INSERT|UPDATE|DELETE)\b[^`]*\$\{', re.IGNORECASE),
        re.compile(r'(query|execute|raw)\s*\(\s*[\'"][^\'"]*\b(SELECT|INSERT|UPDATE|DELETE)\b[^\'"]*[\'"]\s*\+',
                   re.IGNORECASE),
    ],
    'crypto-faible': [
        re.compile(r"""createHash\(\s*['"](md5|sha1)['"]""", re.IGNORECASE),
        re.compile(r'\b(md5|sha1)\s*\(', re.IGNORECASE),
    ],
    'random-non-securise': [
        re.compile(r'(token|secret|password|salt|otp|nonce|api[_-]?key|uuid)[^\n;]{0,40}Math\.random',
                   re.IGNORECASE),
        re.compile(r'Math\.random[^\n;]{0,40}(token|secret|password|salt|otp|nonce)',
                   re.IGNORECASE),
    ],
    'url-http-non-securisee': [
        re.compile(r'http://(?!localhost|127\.0\.0\.1|0\.0\.0\.0|www\.w3\.org|schemas?\.|[^"\'\s/]*\.local)'),
    ],
    # --- React ---
    'react-key-index': [
        re.compile(r'key=\{\s*(index|idx|i)\s*\}'),
    ],
    # --- Erreurs silencieuses (commandement #9) ---
    'catch-log-seulement': [
        re.compile(r'catch\s*\([^)]*\)\s*\{\s*console\.\w+\([^{}]*\)\s*;?\s*\}'),
        re.compile(r'\.catch\(\s*\(?\w*\)?\s*=>\s*console\.\w+\('),
    ],
    'catch-retour-silencieux': [
        re.compile(r'catch\s*\([^)]*\)\s*\{\s*return\s+(null|undefined|\[\]|\{\}|false|0|""|\'\')\s*;?\s*\}'),
    ],
    # --- Dette / qualite ---
    'var-legacy': [
        re.compile(r'(^|\s)var\s+[a-zA-Z_$]'),
    ],
    'egalite-non-stricte': [
        re.compile(r'(?<![=!<>])==(?!=)'),
        re.compile(r'(?<!!)!=(?!=)'),
    ],
}

# Code commente (mort) : un commentaire qui ressemble a du code, pas a de la prose
COMMENTED_CODE = re.compile(
    r'^\s*//\s*(const |let |var |function |return |import |export |if\s*\('
    r'|for\s*\(|while\s*\(|await |[\w$.]+\([^)]*\)\s*;?\s*$|[}\])]\s*;?\s*$)',
    re.MULTILINE,
)

# Type any (echappatoire TS) : uniquement dans les fichiers TypeScript
TYPE_ANY = [
    re.compile(r':\s*any\b'),
    re.compile(r'\bas\s+any\b'),
    re.compile(r'<any>'),
    re.compile(r':\s*any\[\]'),
]

# Hooks React qui doivent porter un tableau de dependances
REACT_HOOKS = re.compile(r'\b(useEffect|useLayoutEffect|useMemo|useCallback)\s*\(')

# Regles "cosmetiques" desactivees dans les fichiers de test (bruit attendu)
TEST_SKIP_RULES = {
    'secret-en-clair', 'egalite-non-stricte', 'var-legacy', 'code-commente',
}

# Regles a syntaxe JS/JSX : sans objet sur du Python (== y est normal, etc.)
JS_ONLY_RULES = {
    'var-legacy', 'egalite-non-stricte', 'react-key-index', 'xss-innerhtml',
    'catch-log-seulement', 'catch-retour-silencieux',
}
TS_EXTENSIONS = {'.ts', '.tsx', '.mts', '.cts'}

# Boilerplate de scaffold laisse tel quel (create-next-app, Vite, CRA...).
# Un etudiant qui n'a pas touche sa page d'accueil = "n'a rien fait" (pire que
# du code sale : du code absent). Detecte le texte par defaut des templates.
BOILERPLATE_MARKERS = re.compile(
    r'To get started, edit|Get started by editing'
    r'|Save and see your changes instantly|Vite \+ React'
    r'|Edit <code>src/App|Learn React|app/page\.tsx file',
    re.IGNORECASE,
)

# Donnees mockees utilisees comme vrai backend (import d'un module mock-data,
# fake-data, etc. dans du code de prod). Faux backend = dette franche.
MOCK_IMPORT = re.compile(
    r'''import\s+[^;]*\bfrom\s+['"][^'"]*(mock[-_]?data|fake[-_]?data|/mocks?)['"]''',
    re.IGNORECASE,
)

# Fichiers de test (leur ABSENCE est la dette : aucun test)
TEST_FILE = re.compile(r'(\.(test|spec)\.[jt]sx?$|__tests__|/(cypress|e2e)/)',
                       re.IGNORECASE)

# Logs : depend du langage (print uniquement en Python)
LOGS_JS_PATTERNS = [
    re.compile(r'console\.(log|debug)\('),
    re.compile(r'\bdebugger\s*;'),
]
LOGS_PY_PATTERNS = [
    re.compile(r'(^|\s)print\('),
]


# --------------------------------------------------------------------------
# Helpers de scan
# --------------------------------------------------------------------------

def line_of(content: str, offset: int) -> int:
    """Numero de ligne (1-indexe) correspondant a un offset dans le contenu."""
    return content.count('\n', 0, offset) + 1


def snippet_at(lines: list[str], line_no: int, limit: int = 120) -> str:
    """Renvoie la ligne ciblee, nettoyee et tronquee, pour l'affichage."""
    if 1 <= line_no <= len(lines):
        text = lines[line_no - 1].strip()
        return text[:limit]
    return ''


def react_hooks_missing_deps(content: str) -> list[int]:
    """Offsets des hooks React appeles sans tableau de dependances.

    Match les parentheses de l'appel : un hook avec deps finit par `])`, un hook
    sans deps finit par `})` (le callback est le seul argument) => bug classique
    (effet rejoue a chaque rendu). Deterministe (comptage de parentheses).
    """
    offsets: list[int] = []
    for match in REACT_HOOKS.finditer(content):
        open_paren = match.end() - 1
        depth = 0
        i = open_paren
        while i < len(content):
            if content[i] == '(':
                depth += 1
            elif content[i] == ')':
                depth -= 1
                if depth == 0:
                    break
            i += 1
        call = content[open_paren:i + 1].rstrip()
        # Se termine par "])" => tableau de deps present. Sinon : manquant.
        if not re.search(r'\]\s*\)$', call):
            offsets.append(match.start())
    return offsets


def is_generated(content: str) -> bool:
    """Detecte un fichier genere via son banniere (15 premieres lignes)."""
    head = '\n'.join(content.split('\n')[:15])
    return bool(GENERATED_MARKERS.search(head))


def build_context(lines: list[str], line_no: int) -> list[dict]:
    """Fenetre de code autour de la ligne fautive (vue GitHub).

    Renvoie une liste de {n, code, cible} : numero de ligne, code brut tronque,
    et un flag indiquant la ligne en cause.
    """
    start = max(1, line_no - CONTEXT_RADIUS)
    end = min(len(lines), line_no + CONTEXT_RADIUS)
    return [
        {
            'n': n,
            'code': lines[n - 1][:MAX_CODE_LINE_LENGTH],
            'cible': n == line_no,
        }
        for n in range(start, end + 1)
    ]


def is_text_readable(path: Path) -> str | None:
    """Lit le fichier en texte ; renvoie None si binaire / minifie / illisible."""
    try:
        content = path.read_text(encoding='utf-8', errors='strict')
    except (UnicodeDecodeError, OSError):
        return None
    # Heuristique minifie : une ligne tres longue => on saute
    for chunk in content.split('\n'):
        if len(chunk) > MAX_LINE_LENGTH_BEFORE_MINIFIED:
            return None
    return content


def iter_source_files(repo: Path):
    """Itere les fichiers source pertinents, en sautant les dossiers ignores."""
    for path in sorted(repo.rglob('*')):
        if not path.is_file():
            continue
        parts = set(path.relative_to(repo).parts)
        if parts & IGNORE_DIRS:
            continue
        if path.name in IGNORE_FILES:
            continue
        if '.min.' in path.name:
            continue
        if path.suffix.lower() in SCAN_EXTENSIONS:
            yield path


# --------------------------------------------------------------------------
# Scan d'un repo
# --------------------------------------------------------------------------

def scan_repo(repo: Path, deep: bool = False) -> dict:
    """Scanne un repo et renvoie le rapport JSON-able (un objet)."""
    repo = repo.resolve()
    report: dict = {
        'repo': repo.name,
        'etudiant': repo.name,
        'total': 0,
        'score': 0,
        'lignesDeCode': 0,
        'modeDeep': deep,
        'parRegle': {key: 0 for key in RULES_LABELS},
        'parSeverite': {sev: 0 for sev in SEVERITY_WEIGHT},
        'exemples': [],
    }

    files = list(iter_source_files(repo))

    # Repo vide ou illisible : marque non analysable, ne crashe pas.
    if not files:
        report['nonAnalysable'] = True
        report['raison'] = 'aucun fichier source detecte'
        return report

    examples_par_regle: dict[str, list[dict]] = {key: [] for key in RULES_LABELS}

    def add_finding(rule: str, rel_file: str, line: int, detail: str,
                    contexte: list[dict] | None = None) -> None:
        report['parRegle'][rule] += 1
        report['total'] += 1
        bucket = examples_par_regle[rule]
        if len(bucket) < MAX_EXAMPLES_PER_RULE:
            exemple = {
                'regle': rule,
                'fichier': rel_file,
                'ligne': line,
                'detail': detail,
            }
            if contexte:
                exemple['contexte'] = contexte
            bucket.append(exemple)

    # --- Regle repo-level : pas de cadre (#1/#5) ---
    has_framing = any(
        entry.is_file() and entry.name.lower() in FRAMING_FILES
        for entry in repo.iterdir()
    )
    if not has_framing:
        add_finding('pas-de-cadre', '.', 1,
                    'aucun CLAUDE.md / PROJECT_RULES.md a la racine')

    # --- Regle repo-level : aucun test ---
    has_tests = any(TEST_FILE.search(str(p.relative_to(repo))) for p in files)
    if not has_tests:
        add_finding('aucun-test', '.', 1,
                    'aucun fichier de test (.test/.spec/__tests__/cypress)')

    # --- Scan fichier par fichier ---
    for path in files:
        rel = str(path.relative_to(repo))
        content = is_text_readable(path)
        if content is None:
            continue
        # Code genere (Prisma, codegen...) : pas la dette de l'etudiant, on saute
        if is_generated(content):
            continue
        lines = content.split('\n')

        # Lignes de code de l'etudiant (fichiers source non generes).
        # splitlines() = compte correct (pas de fausse ligne vide finale, colle a
        # wc -l / aux editeurs). `lines` (split) reste pour l'indexation snippet.
        nb_lines = len(content.splitlines())
        report['lignesDeCode'] += nb_lines

        # God file (#10)
        if nb_lines > GOD_FILE_WARNING:
            gravite = 'grave' if nb_lines > GOD_FILE_GRAVE else 'warning'
            add_finding('god-file', rel, 1, f'{nb_lines} lignes ({gravite})')

        # Nommage paresseux (#4) : stem du fichier
        if path.stem.lower() in LAZY_FILE_STEMS:
            add_finding('nommage-paresseux', rel, 1,
                        f'fichier fourre-tout : {path.name}')

        # Boilerplate non modifie : 1 souci par fichier (premiere ligne marqueur)
        bp = BOILERPLATE_MARKERS.search(content)
        if bp:
            line_no = line_of(content, bp.start())
            add_finding('boilerplate-non-modifie', rel, line_no,
                        'page de scaffold (create-next-app/Vite) non modifiee',
                        build_context(lines, line_no))

        # Donnees mockees : import d'un module mock/fake comme source de donnees
        seen_lines = set()
        for match in MOCK_IMPORT.finditer(content):
            line_no = line_of(content, match.start())
            if line_no in seen_lines:
                continue
            seen_lines.add(line_no)
            add_finding('donnees-mockees', rel, line_no,
                        'import de donnees mockees (pas de vrai backend)',
                        build_context(lines, line_no))

        # Fichiers de test/fixture : secrets et logs y sont attendus (fixtures)
        is_test_fixture = bool(SKIP_LOGS_FILE_HINT.search(rel))

        is_python = path.suffix.lower() == '.py'

        # Regles "ligne" a regex (dedupe par ligne dans une meme regle)
        for rule, patterns in LINE_RULES.items():
            if is_test_fixture and rule in TEST_SKIP_RULES:
                continue
            if is_python and rule in JS_ONLY_RULES:
                continue
            seen_lines: set[int] = set()
            for pattern in patterns:
                for match in pattern.finditer(content):
                    line_no = line_of(content, match.start())
                    if line_no in seen_lines:
                        continue
                    seen_lines.add(line_no)
                    add_finding(rule, rel, line_no, snippet_at(lines, line_no),
                                build_context(lines, line_no))

        # Logs oublies (#10/#11) : selon langage, hors fichiers test/seed/mock
        if not is_test_fixture:
            log_patterns = (LOGS_PY_PATTERNS if path.suffix.lower() == '.py'
                            else LOGS_JS_PATTERNS)
            seen_lines = set()
            for pattern in log_patterns:
                for match in pattern.finditer(content):
                    line_no = line_of(content, match.start())
                    if line_no in seen_lines:
                        continue
                    seen_lines.add(line_no)
                    add_finding('logs-oublies', rel, line_no,
                                snippet_at(lines, line_no),
                                build_context(lines, line_no))

        # Type any : echappatoire TypeScript (uniquement fichiers .ts/.tsx)
        if path.suffix.lower() in TS_EXTENSIONS:
            seen_lines = set()
            for pattern in TYPE_ANY:
                for match in pattern.finditer(content):
                    line_no = line_of(content, match.start())
                    if line_no in seen_lines:
                        continue
                    seen_lines.add(line_no)
                    add_finding('type-any', rel, line_no,
                                snippet_at(lines, line_no),
                                build_context(lines, line_no))

        # Code commente (mort) : commentaire qui ressemble a du code, hors test
        if not is_test_fixture:
            seen_lines = set()
            for match in COMMENTED_CODE.finditer(content):
                line_no = line_of(content, match.start())
                if line_no in seen_lines:
                    continue
                seen_lines.add(line_no)
                add_finding('code-commente', rel, line_no,
                            snippet_at(lines, line_no),
                            build_context(lines, line_no))

        # Hooks React sans tableau de dependances (comptage de parentheses)
        if not is_python:
            for offset in react_hooks_missing_deps(content):
                line_no = line_of(content, offset)
                add_finding('react-hook-sans-deps', rel, line_no,
                            snippet_at(lines, line_no),
                            build_context(lines, line_no))

    # Mode deep : outils externes (gitleaks/trivy/jscpd/tsc) + AST (tree-sitter).
    # Import tolerant : si le module deep n'est pas la (distribution standard),
    # on ignore proprement au lieu de planter.
    if deep:
        try:
            from lint_dette_deep import run_deep_checks
        except ImportError:
            run_deep_checks = None
        if run_deep_checks is None:
            report['deepStatus'] = {'erreur': 'module lint_dette_deep.py absent'}
        else:
            result = run_deep_checks(repo, files, is_generated)
            report['deepStatus'] = result['status']
            for rule, rel_file, line, detail in result['findings']:
                add_finding(rule, rel_file, line, detail)

    # Aplati les exemples (variete : quelques-uns par regle)
    for bucket in examples_par_regle.values():
        report['exemples'].extend(bucket)

    # Score pondere par gravite + repartition critique/majeur/mineur
    for rule, count in report['parRegle'].items():
        severite = RULE_SEVERITY[rule]
        report['score'] += count * SEVERITY_WEIGHT[severite]
        report['parSeverite'][severite] += count

    return report


def scan_all(folder: Path, deep: bool = False) -> list[dict]:
    """Scanne chaque sous-dossier (= un repo clone) et renvoie un tableau."""
    folder = folder.resolve()
    reports: list[dict] = []
    for entry in sorted(folder.iterdir()):
        if not entry.is_dir():
            continue
        if entry.name in IGNORE_DIRS:
            continue
        try:
            reports.append(scan_repo(entry, deep=deep))
        except Exception as exc:  # robustesse : un repo casse n'arrete pas tout
            reports.append({
                'repo': entry.name,
                'etudiant': entry.name,
                'total': 0,
                'score': 0,
                'lignesDeCode': 0,
                'modeDeep': deep,
                'parRegle': {key: 0 for key in RULES_LABELS},
                'parSeverite': {sev: 0 for sev in SEVERITY_WEIGHT},
                'exemples': [],
                'nonAnalysable': True,
                'raison': f'erreur de scan : {exc}',
            })
    return reports


# --------------------------------------------------------------------------
# Historique : empile un instantane par analyse, pour suivre l'evolution
# --------------------------------------------------------------------------

def append_history(path: Path, reports: list[dict]) -> None:
    """Ajoute un instantane horodate (par repo analyse) au fichier historique."""
    try:
        history = json.loads(path.read_text(encoding='utf-8')) if path.exists() else []
    except (json.JSONDecodeError, OSError):
        history = []
    if not isinstance(history, list):
        history = []
    when = datetime.now().isoformat(timespec='seconds')
    for r in reports:
        if r.get('nonAnalysable'):
            continue
        history.append({
            'date': when,
            'repo': r.get('repo'),
            'etudiant': r.get('etudiant'),
            'score': r.get('score', 0),
            'total': r.get('total', 0),
            'lignesDeCode': r.get('lignesDeCode', 0),
            'parSeverite': r.get('parSeverite', {}),
        })
    path.write_text(json.dumps(history, ensure_ascii=False, indent=2), encoding='utf-8')


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Linter de dette IA (deterministe, zero LLM).",
    )
    parser.add_argument('chemin', help="chemin d'un repo, ou dossier de repos avec --all")
    parser.add_argument('--all', action='store_true',
                        help='scanne tous les sous-dossiers comme autant de repos')
    parser.add_argument('--pretty', action='store_true',
                        help='JSON indente et lisible')
    parser.add_argument('--deep', action='store_true',
                        help='lance aussi les outils externes (gitleaks, trivy, '
                             'jscpd, tsc) + AST tree-sitter. Plus lent, toujours '
                             'deterministe, zero LLM.')
    parser.add_argument('--history', metavar='FICHIER',
                        help='empile un instantane horodate de cette analyse dans '
                             'FICHIER (JSON) pour suivre l evolution dans le temps')
    args = parser.parse_args()

    cible = Path(args.chemin)
    if not cible.exists():
        print(f"Chemin introuvable : {cible}", file=sys.stderr)
        return 1

    result = (scan_all(cible, deep=args.deep) if args.all
              else scan_repo(cible, deep=args.deep))

    if args.history:
        reports = result if isinstance(result, list) else [result]
        append_history(Path(args.history), reports)

    indent = 2 if args.pretty else None
    print(json.dumps(result, ensure_ascii=False, indent=indent))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
